name: Deploy to GHCR

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish to GHCR
      uses: docker/build-push-action@v1
      with:
        repository: nint8835/gramfelbot
        username: nint8835
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: ghcr.io
        tags: latest
